# WARNING: as this file contains credentials, be sure to set correct file permissions

# users
[irc]
	[irc.freenode]
	Server="irc.freenode.net:6697"
	Nick="matter"
	RemoteNickFormat=""

	[irc.localhost]
	RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
	Server="localhost:6667"
	Nick="bot"
	NickServPassword="<password>"

# channels
[[gateway]]
name="offtopic"
enable=true
	[[gateway.inout]]
	account="irc.freenode"
	channel="#simplecloud-spam"

	[[gateway.inout]]
	account="irc.localhost"
	channel="#spam"
